# dependabot.yml
version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      sass-related:
        patterns:
          - "*sass*"
      others:
        patterns:
          - "*"
    # Packages released less than 7 days ago will be rejected for installation.
    # Match the min-release-age in .npmrc.
    cooldown:
      default-days: 7
      semver-major-days: 7
      semver-minor-days: 7
      semver-patch-days: 7
  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
